main_temp/main/routes.py
from flask import Blueprint, render_template, url_for
# from main_temp import subjects

main = Blueprint('main', __name__)


@main.route('/home')
def home():
    return render_template('home.html', title='SPJ')#,subjects=subjects)


@main.route('/about')
def about():
    return render_template('about.html', title='About')

main_temp/marks/routes.py
from flask import request, render_template, session, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from main_temp import db, bcrypt
from main_temp.users.forms import RegistrationTeacherForm, RegistrationStudentForm, LoginForm
from main_temp.models import Teachers, Subject, Students, Marks, Classes, Subject_classes
from main_temp.main.forms import Students_form, Add_date_form

marks = Blueprint('marks', __name__)

@marks.route("/table")
@login_required
def table():
    if session['account_type'] == 'Students':
        subject = []
        subjects = Subject_classes.query.filter_by(class_id=current_user.class_id)
        for i in subjects:
            subject.append(i.subject_id)
        subjects = []
        for i in subject:
            temps = Subject.query.filter_by(id=i).first()
            subjects.append(temps.name)
        return render_template('layout.html', title='Table', subjects=subjects)
    elif session['account_type'] == 'Teachers':
        teacher = Teachers.query.filter_by(id=current_user.id).first()
        teacher = teacher.teacher_subject
        subjects = []
        for i in teacher:
            temps = i.subject_class
            subjects.append(temps)
        classes_and_subjects = {}
        final_classes_and_subjects = {}
        unique_classes_ids = []
        for i in subjects:
            for j in i:
                if j.class_id not in unique_classes_ids:
                    unique_classes_ids.append(j.class_id)
        for i in unique_classes_ids:
            temps = Subject_classes.query.filter_by(class_id=i)
            classes_and_subjects[i] = []
            for j in temps:
                classes_and_subjects[i].append(j.subject_id)
        for i in classes_and_subjects:
            class_name = Classes.query.filter_by(id=i).first().name
            final_classes_and_subjects[class_name] = []
            for j in classes_and_subjects[i]:
                subject_name = Subject.query.filter_by(id=j).first().name
                final_classes_and_subjects[class_name].append(subject_name)
        return render_template('layout.html', title='Table',
                               classes_and_subjects=final_classes_and_subjects)

@marks.route("/table/")
@marks.route("/table/<subject_name>/<class_name>")
@marks.route("/table/<subject_name>/<class_name>/<student_name>", methods=['GET', 'POST'])
@login_required
def table_with_variables(subject_name, class_name, student_name='show'):
    if session['account_type'] == 'Students':
        subject = []
        subjects = Subject_classes.query.filter_by(class_id=current_user.class_id)
        for i in subjects:
            subject.append(i.subject_id)
        subjects = []
        for i in subject:
            temps = Subject.query.filter_by(id=i).first()
            subjects.append(temps.name)

        temp = Subject.query.filter_by(name=subject_name).first()
        current_subject = Marks.query.filter_by(class_id=current_user.class_id,
                                                student_id=current_user.id,
                                                subject_id=temp.id)
        return render_template('table.html', title='Table', marks_=current_subject, subjects=subjects)
    if session['account_type'] == 'Teachers':
        adding_bool = False
        students_form = Students_form()
        if request.method == "POST":
            if request.form["submit_button"] == "Load Student":
                student_name = students_form.students.data
            if request.form["submit_button"] == "Add new date":
                adding_bool = True
                adding_form = Add_date_form()
                if adding_form.validate():
                    print("valid")
                print(adding_form.errors)
                if adding_form.validate_on_submit():
                    date = adding_form.date.data
                    type = adding_form.type.data
                    class_id = Classes.query.filter_by(name=class_name).first().id
                    student_id = Students.query.filter_by(fullname=student_name, class_id=class_id).first().id
                    subject_id = Subject.query.filter_by(name=subject_name).first().id
                    new_mark = Marks(subject_id=subject_id, student_id=student_id,
                                     teacher_id=current_user.id, class_id=class_id,
                                     date=date, type=type)
                    db.session.add(new_mark)
                    db.session.commit()
        if class_name and class_name is not None and student_name and student_name is not None:
            class_id = Classes.query.filter_by(name=class_name).first().id
            if student_name == 'show':
                student_name = Students.query.filter_by(class_id=class_id).first().fullname
            student_id = Students.query.filter_by(fullname=student_name, class_id=class_id).first().id
            subject_id = Subject.query.filter_by(name=subject_name).first().id
            current_subject = Marks.query.filter_by(subject_id=subject_id,
                                                    teacher_id=current_user.id,
                                                    class_id=class_id,
                                                    student_id=student_id)
        teacher = Teachers.query.filter_by(id=current_user.id).first()
        teacher = teacher.teacher_subject
        subjects = []
        for i in teacher:
            temps = i.subject_class
            subjects.append(temps)
        current_subject_students = Classes.query.filter_by(id=class_id).first().class_students
        for i in current_subject_students:
            student = i.fullname
            if student not in students_form.students.choices:
                students_form.students.choices.append(student)
        classes_and_subjects = {}
        final_classes_and_subjects = {}
        unique_classes_ids = []
        for i in subjects:
            for j in i:
                if j.class_id not in unique_classes_ids:
                    unique_classes_ids.append(j.class_id)
        for i in unique_classes_ids:
            temps = Subject_classes.query.filter_by(class_id=i)
            classes_and_subjects[i] = []
            for j in temps:
                classes_and_subjects[i].append(j.subject_id)
        for i in classes_and_subjects:
            class_name_ = Classes.query.filter_by(id=i).first().name
            final_classes_and_subjects[class_name_] = []
            for j in classes_and_subjects[i]:
                subject_name_ = Subject.query.filter_by(id=j).first().name
                final_classes_and_subjects[class_name_].append(subject_name_)
        if adding_bool:
            return render_template('table_for_teacher.html', title='Table', marks_=current_subject,
                               classes_and_subjects=final_classes_and_subjects, student_name=student_name,
                               form=students_form, adding_form=adding_form)
        else:
            return render_template('table_for_teacher.html', title='Table', marks_=current_subject,
                                   classes_and_subjects=final_classes_and_subjects, student_name=student_name,
                                   form=students_form)

main_temp/users/routes.py
from flask import render_template, url_for,session, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from main_temp import db, bcrypt, login_manager, app
from main_temp.users.forms import RegistrationTeacherForm, RegistrationStudentForm, LoginForm
from  main_temp.models import Teachers, Subject, Students, Marks, Classes, Subject_classes


users = Blueprint('users', __name__)
main_user = Blueprint("main_user", __name__)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        teacher = Teachers.query.filter_by(email=form.email.data).first()
        student = Students.query.filter_by(email=form.email.data).first()
        if teacher and bcrypt.check_password_hash(teacher.password, form.password.data):
            login_user(teacher, remember=form.remember.data)
            next_page = request.args.get('next')
            session['account_type'] = 'Teachers'
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        elif student and bcrypt.check_password_hash(student.password, form.password.data):
            login_user(student, remember=form.remember.data)
            next_page = request.args.get('next')
            session['account_type'] = 'Students'
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/register_teacher", methods=['GET', 'POST'])
def register_teacher():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationTeacherForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        teacher = Teachers(fullname=form.fullname.data, email=form.email.data, password=hashed_password)
        db.session.add(teacher)
        db.session.commit()
        flash(f'Account created for {form.fullname.data}!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register_teacher.html', title='Register', form=form)


@users.route("/register_student", methods=['GET', 'POST'])
def register_student():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationStudentForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        temp = Classes.query.filter_by(name=form.class_.data).first()
        student = Students(fullname=form.fullname.data, email=form.email.data, members=temp, password=hashed_password)
        db.session.add(student)
        db.session.commit()
        flash(f'Account created for {form.fullname.data}!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register_student.html', title='Register', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account")
@login_required
def account():
    return render_template('account.html', title='Account')


@login_manager.user_loader
def load_user(user_id):
    if session['account_type'] == 'Students':
        return Students.query.get(int(user_id))
    elif session['account_type'] == 'Teachers':
        return Teachers.query.get(int(user_id))


    # if app.config['APPLICATION_ROOT'] == '/teacher':
    #     print('abcs')
    #     return Teachers.query.get(int(user_id))
    # elif app.config['APPLICATION_ROOT'] == '/student':
    #     print('abcasfs')
    #     return Students.query.get(int(user_id))
    # else:
    #     print("sadaf")

main_temp/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <hi>About Page</hi>
{% endblock content %}

main_temp/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.fullname }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
    </div>
{% endblock content %}

main_temp/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <hi>Home page</hi>
{% endblock content %}

main_temp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    <meta charset="UTF-8">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Sample title</title>
    {% endif %}
</head>
<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">Student Perfomance Journal</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            <a class="nav-item nav-link" href="{{ url_for('marks.table') }}">Grades</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
            <a class="nav-item nav-link" href="{{ url_for('users.register_teacher') }}">Register Teacher</a>
            <a class="nav-item nav-link" href="{{ url_for('users.register_student') }}">Register Student</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>

        {% if subjects %}
        <div class="col-md-4">
          <div class="content-section">
            <h3>Subjects</h3>
            <div class="list-group">
              {% for i in subjects %}
              <a class="list-group-item list-group-item-light" href="{{ url_for('marks.table_with_variables', class_name=None, subject_name=i )}}">{{i}}</a>
              {% endfor %}
            </div>
          </div>
        </div>
        {% endif %}

        {% if classes_and_subjects %}
        <div class="col-md-4">
          <div class="content-section">
            <h3>Subjects</h3>
            <div class="list-group">
              {% for i in classes_and_subjects%}
              <a class="list-group-item">{{i}}</a>
              {% for j in classes_and_subjects[i] %}
              {% if student_name %}
              <a class="list-group-item list-group-item-light" href="{{ url_for('marks.table_with_variables', class_name=i, subject_name=j, student_name=student_name)}}">{{j}}</a>
              {% else %}
              <a class="list-group-item list-group-item-light" href="{{ url_for('marks.table_with_variables', class_name=i, subject_name=j)}}">{{j}}</a>
              {% endif %}
              {% endfor %}
              {% endfor %}
            </div>
          </div>
        </div>
        {% endif %}

      </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

main_temp/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

main_temp/templates/register_student.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.fullname.label(class="form-control-label") }}

                    {% if form.fullname.errors %}
                        {{ form.fullname(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.fullname.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.fullname(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.class_.label(class="form-control-label") }}

                    {% if form.class_.errors %}
                        {{ form.class_(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.class_.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.class_(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>
    </div>
{% endblock content %}

main_temp/templates/register_teacher.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.fullname.label(class="form-control-label") }}

                    {% if form.fullname.errors %}
                        {{ form.fullname(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.fullname.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.fullname(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>
    </div>
{% endblock content %}

main_temp/templates/table.html
{% extends "layout.html" %}
{% block content %}
    <div class="table-responsive" >
        <table class="table table-bordered">
            <tr><th style="position: sticky; background-color: white; left: 0"></th>
                {% for i in marks_ %}
                <td>{{i.date}}</td>
                {% endfor %}
            </tr>
            <tr>
                <th style="position: sticky; background-color: white; left: 0"></th>
                {% for i in marks_ %}
                <td>{{i.type}}</td>
                {% endfor %}
            </tr>
            <tr>
                <th style="position: sticky; background-color: white; left: 0">{{ current_user.fullname.split()[0] }}</th>
                {% for i in marks_ %}
                <td>{{i.mark}}</td>
                {% endfor %}
            </tr>

        </table>
    </div>
{% endblock content %}

main_temp/templates/table_for_teacher.html
{% extends "layout.html" %}
{% block content %}
    <form method="POST">
        {{ form.students }}
        <input type="submit" name="submit_button" value="Load Student">
    </form>
    <form method="POST">
        {% if adding_form %}
        {{ adding_form.csrf_token }}
        <div>
            {{ adding_form.date.label(class="form-control-label") }}
            {{ adding_form.date}}
        </div>
        <div>
            {{ adding_form.type.label(class="form-control-label") }}
            {{ adding_form.type}}
        </div>
        {% endif %}
        <input type="submit" name="submit_button" value="Add new date">
    </form>
    <div class="table-responsive">
        <table class="table table-bordered">
            <tr><th style="position: sticky; background-color: white; left: 0"></th>
                {% for i in marks_ %}
                <td>{{i.date}}</td>
                {% endfor %}
            </tr>
            <tr>
                <th style="position: sticky; background-color: white; left: 0"></th>
                {% for i in marks_ %}
                <td>{{i.type}}</td>
                {% endfor %}
            </tr>
            <tr>
                <th style="position: sticky; background-color: white; left: 0">{{ student_name.split()[0] }}</th>
                {% for i in marks_ %}
                <td>{{i.mark}}</td>
                {% endfor %}
            </tr>
        </table>
    </div>
{% endblock content %}

main_temp/templates/temp_table.html
<!--{% extends "layout.html" %}-->
<!--{% block content %}-->
<!--    <div class="table-responsive" >-->
<!--        <table class="table table-bordered">-->
<!--            <tr><th style="position: sticky; background-color: white; left: 0">{{ current_user.fullname }}</th><td>QWERTYUIOPASDFGHJKLZXCVBNM</td><td>QWERTYUIOPASDFGHJKLZXCVBNM</td></tr>-->
<!--            <tr><th style="position: sticky; background-color: white; left: 0">2</th><td>QWERTYUIOPASDFGHJKLZXCVBNM</td><td>QWERTYUIOPASDFGHJKLZXCVBNM</td></tr>-->
<!--          </table>-->
<!--    </div>-->
<!--{% endblock content %}-->